#cloud-config
cloud_init_modules:
  - migrator
  - cc_disk_setup
  - bootcmd
  - write-files
  - growpart
  - resizefs
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - rsyslog
  - users-groups
  - ssh
cloud_config_modules:
  - mounts
  - locale
  - set-passwords
  - yum-add-repo
  - timezone
  - disable-ec2-metadata
  - runcmd
  - package-update-upgrade-install
cloud_final_modules:
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - scripts-user
  - ssh-authkey-fingerprints
  - keys-to-console
  - final-message
hostname: {{reposerver_hostname}}
fqdn: {{reposerver_fqdn}}
manage_etc_hosts: true
debug: true
output: { all: "| tee -a /var/log/cloud-init-output.log" }
package_upgrade: false
users:
  - default
  - name: stack
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: wheel,adm
    ssh_pwauth: True
    ssh_authorized_keys:
      - {{IDRSAPUB}}
  - name: root
    ssh_authorized_keys:
      - {{IDRSAPUB}}
ssh_pwauth: True
disable_root: false
chpasswd:
  list: |
    root:toor
    stack:stack
  expire: false
write_files:
  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    content: |
      DEVICE=eth0
      ONBOOT=yes
      IPADDR={{reposerver_ip}}
      NETMASK=255.255.255.0
      GATEWAY=192.168.122.1
      DNS1=192.168.122.1

runcmd:
  # - subscription-manager register --username={{rhn_username}} --password={{rhn_password}}
  # - subscription-manager attach --pool={{pool}}
  # - subscription-manager repos --disable=*
  # - subscription-manager repos  --enable=rhel-7-fast-datapath-rpms --enable=rhel-7-server-openstack-13-devtools-rpms --enable=rhel-7-server-openstack-13-rpms --enable=rhel-7-server-ose-3.1--rpms --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms  --enable=rhel-7-server-rhceph-2-mon-rpms --enable=rhel-7-server-rhceph-2-osd-rpms --enable=rhel-7-server-openstack-13-optools-rpms --enable=rhel-7-server-optional-rpms
  - yum remove cloud-init -y
  - reboot
packages:
  - wget
  - httpd
  - yum-utils
  - createrepo
  - git
  - screen
  - vim
  - tmux

fs_setup:
 - label: None
   filesystem: 'ext4'
   device: '/dev/vdb'
   partition: 'auto'

mounts:

 - [ /dev/vdb, /OSPOCP, "ext4", "defaults,noatime"]

mount_default_fields: [ None, None, "ext4", "defaults,noatime", "0","2" ]
