---

  - name: upgrade redhat
    yum: name=* state=latest
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
  - name: upgrade ubuntu
    apt: name=* state=latest
    when: ansible_distribution == 'ubuntu' or ansible_distribution == 'debian'  
