---

  - name: create network
    virt_net: command=define name={{item}} xml='{{ lookup('file', '{{ playbook_dir }}/roles/kvm-host/files/{{item}}.xml') }}'
  - name: set nets as active
    virt_net: state=active  name={{item}}
  - name: set autostart for all nets
    virt_net: autostart=yes name={{item}}
  # - name: start  all nets
  #   virt_net: start=yes name={{item}}
