---
   - name: generate cloud drive for rhel
     include: generate-cloud-drive-rhel.yml
     when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

   - name: generate cloud drive for Fedora
     include: generate-cloud-drive-fed.yml
     when: ansible_distribution == "Fedora" or ansible_distribution == 'Ubuntu'

   - name: Copy preseeded qcow2 file and use it as a base for undercloud creation
     copy: remote_src=True src=/var/lib/libvirt/images/{{undercloud_hostname}}-matrix.qcow2 dest=/var/lib/libvirt/images/{{undercloud_hostname}}.qcow2

   - name: create {{undercloud_hostname}} vm
     command: >
       virt-install --ram 32000 --vcpus 12 --os-variant rhel7 \
       --disk path=/var/lib/libvirt/images/{{undercloud_hostname}}.qcow2,device=disk,bus=virtio,format=qcow2 \
       --disk path=/var/lib/libvirt/images/{{undercloud_hostname}}-drive.img,device=disk,bus=virtio,format=qcow2 \
       --import --noautoconsole --vnc \
       --network network:net-provisioning \
       --network network:default \
       --cpu host-passthrough \
       --name {{undercloud_hostname}}
  #  - name: Detach cloud-drive
  #    command: >
  #     virsh detach-disk --persistent {{undercloud_hostname}} /var/lib/libvirt/images/{{undercloud_hostname}}-drive.img
