- name: Reboot and wait...
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: pause until ssh connection comes back
  pause:
    minutes: 1


# - name: Waiting for server to come back...
#   local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300
